const express = require('express');
const router = express.Router();
const multer = require('multer');
const axios = require('axios');

// Configure multer for memory storage
const upload = multer({
    storage: multer.memoryStorage(),
    limits: {
        fileSize: 50 * 1024 * 1024 // 50MB limit
    }
});

/**
 * @route   POST /api/upload
 * @desc    Proxy PDF upload to Python AI service on Render
 * @access  Public
 */
router.post('/', upload.single('file'), async (req, res) => {
    try {
        console.log('📄 PDF Upload via /api/upload - Proxying to Python service');

        if (!req.file) {
            return res.status(400).json({
                success: false,
                message: 'No file uploaded'
            });
        }

        console.log(`📤 File: ${req.file.originalname} (${req.file.size} bytes)`);

        // Prepare FormData for Python service
        const FormData = require('form-data');
        const form = new FormData();
        form.append('file', req.file.buffer, {
            filename: req.file.originalname,
            contentType: req.file.mimetype
        });

        // Python service URL
        const pythonUrl = process.env.PYTHON_SERVICE_URL || 'https://clone-quizito.onrender.com';
        const endpoint = `${pythonUrl.replace(/\/$/, '')}/api/upload`;

        console.log(`🔗 Forwarding to: ${endpoint}`);
        console.log('⏱️  May take 1-2 minutes on cold start...');

        // Forward to Python service
        const pythonResponse = await axios.post(endpoint, form, {
            headers: {
                ...form.getHeaders()
            },
            timeout: 180000, // 3 minutes
            maxBodyLength: Infinity,
            maxContentLength: Infinity
        });

        console.log('✅ Python service responded');
        console.log('📦 Response type:', typeof pythonResponse.data);

        // Check response - Strict Array Expectation
        const questionsData = pythonResponse.data;

        if (!Array.isArray(questionsData)) {
            console.error('❌ Invalid format - Expected array, got:', typeof questionsData);
            return res.status(500).json({
                success: false,
                message: 'Invalid response from AI service',
                error: 'Expected array of questions directly from Python service'
            });
        }

        // Normalize question format
        const formattedQuestions = questionsData.map((q, index) => {
            const safeOptions = (q.options || []).map(opt => String(opt).trim());
            const safeAnswer = String(q.answer || '').trim();

            // Try to find correct answer index, default to 0 if not found
            let correctIndex = 0;
            if (safeAnswer && safeAnswer !== 'PLACEHOLDER') {
                const foundIndex = safeOptions.findIndex(opt =>
                    opt.toLowerCase() === safeAnswer.toLowerCase()
                );
                if (foundIndex !== -1) correctIndex = foundIndex;
            }

            return {
                question: String(q.question || 'Question not provided'),
                options: safeOptions,
                correctAnswer: correctIndex, // Computed index preferred over hardcoded 0
                explanation: q.answer || "Generated by AI",
                difficulty: "medium",
                order: index + 1,
                type: 'multiple-choice',
                points: 100,
                timeLimit: 30
            };
        });

        console.log(`✅ Normalized ${formattedQuestions.length} questions from Python service`);

        // Return in standard quiz format
        res.json({
            success: true,
            quiz: {
                title: `Quiz from ${req.file.originalname}`,
                category: 'General',
                difficulty: 'medium',
                questions: formattedQuestions,
                metadata: {
                    source: 'python-ai-service',
                    filename: req.file.originalname,
                    questionsGenerated: formattedQuestions.length
                }
            }
        });

    } catch (error) {
        console.error('❌ Upload proxy error:', error.message);
        if (error.response) {
            console.error('🔴 Status:', error.response.status);
            console.error('🔴 Data:', JSON.stringify(error.response.data).substring(0, 500));
            console.error('🔴 Headers:', JSON.stringify(error.response.headers));
        } else if (error.request) {
            console.error('🔴 No response received (Network/Timeout)');
        }

        if (error.code === 'ECONNABORTED' || error.message.includes('timeout')) {
            return res.status(504).json({
                success: false,
                message: 'AI service timeout. The service is starting up, please try again in 30 seconds.',
                code: 'TIMEOUT'
            });
        }

        if (error.response) {
            return res.status(error.response.status || 500).json({
                success: false,
                message: 'AI service error',
                error: error.response.data
            });
        }

        res.status(500).json({
            success: false,
            message: error.message || 'Failed to process PDF',
            error: 'Internal server error'
        });
    }
});

module.exports = router;
