const express = require('express');
const router = express.Router();
const multer = require('multer');
const axios = require('axios');

// Configure multer for memory storage
const upload = multer({
    storage: multer.memoryStorage(),
    limits: {
        fileSize: 50 * 1024 * 1024 // 50MB limit
    }
});

/**
 * @route   POST /api/upload
 * @desc    Proxy PDF upload to Python AI service on Render
 * @access  Public
 */
router.post('/', upload.single('file'), async (req, res) => {
    try {
        console.log('📄 PDF Upload via /api/upload - Proxying to Python service');

        if (!req.file) {
            return res.status(400).json({
                success: false,
                message: 'No file uploaded'
            });
        }

        console.log(`📤 File: ${req.file.originalname} (${req.file.size} bytes)`);

        // Prepare FormData for Python service
        const FormData = require('form-data');
        const form = new FormData();
        form.append('file', req.file.buffer, {
            filename: req.file.originalname,
            contentType: req.file.mimetype
        });

        // Python service URL
        const pythonUrl = process.env.PYTHON_SERVICE_URL || 'https://clone-quizito.onrender.com';
        const endpoint = `${pythonUrl.replace(/\/$/, '')}/api/upload`;

        console.log(`🔗 Forwarding to: ${endpoint}`);
        console.log('⏱️  May take 1-2 minutes on cold start...');

        // Forward to Python service
        const pythonResponse = await axios.post(endpoint, form, {
            headers: {
                ...form.getHeaders()
            },
            timeout: 180000, // 3 minutes
            maxBodyLength: Infinity,
            maxContentLength: Infinity
        });

        console.log('✅ Python service responded');
        console.log('📦 Response type:', typeof pythonResponse.data);

        // Check if it's an error response
        const responseData = pythonResponse.data;

        if (responseData && typeof responseData === 'object' && !Array.isArray(responseData)) {
            if (responseData.question && responseData.question.includes('Failed')) {
                console.error('❌ Python service error:', responseData.question);
                return res.status(500).json({
                    success: false,
                    message: 'Failed to generate quiz from PDF',
                    error: responseData.question,
                    suggestions: [
                        'PDF might be corrupted or unreadable',
                        'PDF contains mostly images without extractable text',
                        'Try a different PDF with clear, readable text'
                    ]
                });
            }
        }

        // Validate response is an array
        if (!Array.isArray(responseData)) {
            console.error('❌ Invalid response format:', responseData);
            return res.status(500).json({
                success: false,
                message: 'Invalid response from AI service',
                error: 'Expected array of questions',
                receivedType: typeof responseData
            });
        }

        // Transform Python response to our format
        const questions = responseData.map((q, index) => {
            const safeOptions = (q.options || []).map(opt => String(opt).trim());
            const safeAnswer = String(q.answer || '').trim();

            // Determine correct answer index
            let correctIndex = 0; // Default to first option

            if (safeAnswer && safeAnswer !== 'PLACEHOLDER' && safeAnswer !== '') {
                correctIndex = safeOptions.findIndex(opt =>
                    opt.toLowerCase() === safeAnswer.toLowerCase()
                );
                if (correctIndex === -1) {
                    correctIndex = safeOptions.findIndex(opt =>
                        opt.toLowerCase().includes(safeAnswer.toLowerCase()) ||
                        safeAnswer.toLowerCase().includes(opt.toLowerCase())
                    );
                }
            }

            if (correctIndex === -1) correctIndex = 0;

            // Ensure at least 4 options
            while (safeOptions.length < 4) {
                safeOptions.push(`Option ${String.fromCharCode(65 + safeOptions.length)}`);
            }

            return {
                question: String(q.question || 'Question not provided'),
                options: safeOptions,
                correctAnswer: correctIndex,
                type: 'multiple-choice',
                explanation: q.explanation || 'Generated by AI from your PDF',
                difficulty: q.difficulty || 'medium',
                points: 100,
                timeLimit: 30
            };
        });

        console.log(`✅ Transformed ${questions.length} questions`);

        // Return in our standard format
        res.json({
            success: true,
            quiz: {
                title: `AI Quiz from ${req.file.originalname}`,
                category: 'General',
                difficulty: 'medium',
                questions: questions,
                metadata: {
                    source: 'python-ai-service',
                    filename: req.file.originalname,
                    questionsGenerated: questions.length
                }
            }
        });

    } catch (error) {
        console.error('❌ Upload proxy error:', error.message);

        if (error.code === 'ECONNABORTED' || error.message.includes('timeout')) {
            return res.status(504).json({
                success: false,
                message: 'AI service timeout. The service is starting up, please try again in 30 seconds.',
                code: 'TIMEOUT'
            });
        }

        if (error.response) {
            console.error('Python service error:', error.response.data);
            return res.status(error.response.status || 500).json({
                success: false,
                message: 'AI service error',
                error: error.response.data
            });
        }

        res.status(500).json({
            success: false,
            message: error.message || 'Failed to process PDF',
            error: 'Internal server error'
        });
    }
});

module.exports = router;
